const INITIAL_LEVELS = 3;

const PLAYER_HEIGHT_PX = 150;
const PLAYER_MOVE_SPEED_PX = 30;
const PLAYER_DEFAULT_ENERGY = 40;
const PLAYER_MAX_ENERGY = 60;
const PLAYER_ENERGY_GAIN = 10;

const WALL_CHANCE_ADD_TREE = 5;
const FLOOR_CHANCE_ADD_FOOD = 0.5;
const FLOOR_CHANCE_ADD_POINT = 2;
const LEVEL_TILES_IN_SCREEN = 10;

const BACKGROUND_WIDTH = 800;
const BACKGROUND_HEIGHT = 600;
const BACKGROUND_SCROLL_SPEED_PX = 8;

const DECREASE_ENERGY_DELAY_MS = 1000;
const VERIFY_PLAYER_ALIVE_DELAY_MS = 100;
const UPDATE_BACKGROUND_DELAY_MS = 25;
const DETECT_COLLISIONS_DELAY_MS = 5;
