const BACKGROUND_SCROLL_SPEED_PX = 10;
const INITIAL_LEVELS = 3;
const LEVEL_TILES_IN_SCREEN = 10;

const DECREASE_ENERGY_DELAY_MS = 1000;
const VERIFY_PLAYER_ALIVE_DELAY_MS = 100;
const UPDATE_BACKGROUND_DELAY_MS = 25;
const DETECT_COLLISIONS_DELAY_MS = 10;
